### ISSUE TITLE
cpu/cc26x0: timer broken

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#5361] opened 2016-04-20 06:33 UTC
The `timer` implementation on the `cc26x0` is not working a 100% reliable. Most of the `xtimer_` tests fail at the moment. See also discussion in #4675

**Comment by kYc0o** [comment] 2016-07-26 12:34
The issue is still present AFAIK, so postponed for the next release.

**Comment by shaolinkhoa** [comment] 2017-03-14 11:00
Hi,
Are there any news ?
I tested timer_periodic_wakeup with cc2650 launchpad and it didn't work correcly. 
regards,
khoa

**Comment by PeterKietzmann** [comment] 2017-03-28 19:46
@A-Paul can you check if the issue still persists?

**Comment by smlng** [comment] 2017-07-12 08:52
should be fixed by #7335  and #7343

**Comment by smlng** [comment] 2017-08-30 19:46
closing, resolved by #7335 and followups

**Closed by smlng** 2017-08-30 19:46 UTC
Labels: arm, bug, Device driver, timer
