### ISSUE TITLE
valgrind not available for Fedora 31

### ISSUE THREAD

**Issue by Ciusss89** [RIOT-OS/RIOT#13950] opened 2020-04-25 17:17 UTC
#### Description

Valgrind fails to star on Fedora because Fedora 31 drops the 32-bit i686 support
#### Steps to reproduce the issue
```
~/mcu/RIOT/examples/hello-world (master) $ make BOARD=native all term-valgrind
Building application "hello-world" for "native" with MCU "native".

"make" -C /home/giuseppe/mcu/RIOT/boards/native
"make" -C /home/giuseppe/mcu/RIOT/boards/native/drivers
"make" -C /home/giuseppe/mcu/RIOT/core
^["make" -C /home/giuseppe/mcu/RIOT/cpu/native
"make" -C /home/giuseppe/mcu/RIOT/cpu/native/periph
"make" -C /home/giuseppe/mcu/RIOT/cpu/native/stdio_native
"make" -C /home/giuseppe/mcu/RIOT/cpu/native/vfs
"make" -C /home/giuseppe/mcu/RIOT/drivers
"make" -C /home/giuseppe/mcu/RIOT/drivers/periph_common
"make" -C /home/giuseppe/mcu/RIOT/sys
"make" -C /home/giuseppe/mcu/RIOT/sys/auto_init
   text	   data	    bss	    dec	    hex	filename
  21980	    376	  47728	  70084	  111c4	/home/giuseppe/mcu/RIOT/examples/hello-world/bin/native/hello-world.elf
valgrind --leak-check=full --track-origins=yes --fullpath-after=/home/giuseppe/mcu/RIOT/ --read-var-info=yes /home/giuseppe/mcu/RIOT/examples/hello-world/bin/native/hello-world.elf 
valgrind: failed to start tool 'memcheck' for platform 'x86-linux': No such file or directory
make: *** [/home/giuseppe/mcu/RIOT/boards/native/Makefile.include:143: term-valgrind] Error 1
~/mcu/RIOT/examples/hello-world (master) $ 
```

**Comment by miri64** [comment] 2020-04-30 07:31
> […] because Fedora 31 drops the 32-bit i686 support

So this is basically a duplicate of https://github.com/RIOT-OS/RIOT/issues/6603

**Closed by miri64** 2020-04-30 07:31 UTC
Labels: Platform: native, Type: new feature
