### ISSUE TITLE
ESP32 ADC Reading Problem

### ISSUE THREAD

**Issue by mmaxus35** [RIOT-OS/RIOT#12482] opened 2019-10-17 08:35 UTC
I have a following code excerpt ( sorry i have no internet connection right now on my desktop so i write the necessary excerpt of my code on mobile phone)

```c
adc_t g15= GPIO15;
void main(){
    adc_init(g15);  /* it initializes and does not return. -1 */

    while(1){
        printf("Value=%d",adc_sample(g4,ADC_RES_12BIT);
        xtimer_sleep(1);
    }
}
```
My question is what is the step that i missed not to get the result or is it a bug?. It always prompt 4095 or 0 to screen. In my hardware design i made a voltage divider circuit with a 4.7k and a LDR. I measured ldr and it was 2.7 volts when sample results was 4095.

I also tried different pins but i got the same results. In other pins when there is 2.7 volts on a pin it prompts 0 value. However, in digital read it works fine.

@gschorcht

**Comment by gschorcht** [comment] 2019-10-17 12:32
Have you tried to set the attenuation with [adc_set_attenuation](https://riot-os.org/api/adc__arch_8h.html#a6786cc4a1c5602bf2466638ab3e8dff6) as described for [ESP32 ADC channels](https://riot-os.org/api/group__cpu__esp32.html#esp32_adc_channels)? It should be by default 11 dB, that is the voltage could be in range of 0 ... 3.3 V. But maybe there is a problem with the default setting.

**Comment by gschorcht** [comment] 2019-10-18 12:27
@mmaxus35 I have tested it again with 
```
CFLAGS='-DADC_GPIOS="{ GPIO15 }"' make BOARD=esp32-wroom-32 -C tests/periph_adc/ flash
```
and it prints different values in the range from 0 at 0 V to 1024 at 3.3 V. When I change `RES` in `tests/periph_adc/` to `ADC_RES_12BIT`, it prints different values between 0 and 4096.

**Comment by gschorcht** [comment] 2019-10-18 12:28
> I also tried different pins but i got the same results. In other pins when there is 2.7 volts on a pin it prompts 0 value. However, in digital read it works fine.

Please note that not all the GPIOs can be used as ADC channels, please refer the [documentation](https://riot-os.org/api/group__cpu__esp32.html#esp32_adc_channels).

**Comment by gschorcht** [comment] 2019-10-18 12:30
**State:** Can't reproduce the issue. Everything is working as it should for me.

**Comment by mmaxus35** [comment] 2019-10-19 06:14
I run succesfully the tests/periph_adc example and i can implement it to my
code. I tried to use GPIO15 without using CFLAGS i think that's why it did
not work at first place. Sorry for taking your time. I close this issue.

18 Eki 2019 Cum 15:30 tarihinde Gunar Schorcht <notifications@github.com>
şunu yazdı:

**Comment by gschorcht** [comment] 2019-10-19 08:31
> I run succesfully the tests/periph_adc example and i can implement it to my
code. I tried to use GPIO15 without using CFLAGS i think that's why it did
not work at first place.

The reason for this is that the `adc_*` functions do not use a GPIO as argument but a line. A line is the index of an ADC channel assigned to any GPIO. In ESP32, this mapping is configured by the `ADC_GPIOS` macro.

>  The module that causes this problem is " USEMODULE+= auto_init_gnrc_netif ".

I don't see how module `auto_init_gnrc_netif` should affect the ADC configuration.

**Comment by mmaxus35** [comment] 2019-10-19 10:35
In my makefile i commented out all modules step by step and to find which
module causes this problem. At last, i activated the module auto_init_gnrc
and it started to show max and min values. Could you reproduce this problem
when this module is activated. I used the same code in tests/periph_adc

19 Eki 2019 Cmt 11:31 tarihinde Gunar Schorcht <notifications@github.com>
şunu yazdı:

**Comment by gschorcht** [comment] 2019-10-19 13:03
Ok, you didn't describe it correct. The problem seems to be the WiFi module. Without `esp_wifi`, everything works fine, with `esp_wifi` it works as long as `auto_init_gnrc_netif` is not used. The reason is that the WiFi interface is not initialized. Once `auto_initi_gnrc_netif` is used, the WiFi interface is initialized if module `esp_wifi` is used. That is, `esp_wifi` and `auto_init_gnrc_net` have tp be enabled to see the problem:
```
USEMODULE='auto_init_gnrc esp_wifi' CFLAGS='-DADC_GPIOS="{ GPIO15 }"' make BOARD=esp32-wroom-32 -C tests/periph_adc/ flash term
```
Honestly, I have no idea what the problem might be. The ESP32 documentation doesn't say anything about a limited ADC availability if the WiFi module is used.

**Comment by gschorcht** [comment] 2019-10-19 13:21
After some more testing, I figured out that the GPIOs of ADC1 controller work if the WiFi module is enabled while the GPIOs of ADC2 controller don't.

You will find which GPIOs are provided by which ADC controller [here](https://riot-os.org/api/group__cpu__esp32.html#esp32_adc_channels):

- ADC1 supports 8 channels: GPIOs 32-39
- ADC2 supports 10 channels: GPIOs 0, 2, 4, 12-15, 25-27

Please try the following:
```
USEMODULE='auto_init_gnrc_netif esp_wifi' CFLAGS='-DADC_GPIOS="{ GPIO32, GPIO33, GPIO34, GPIO35, GPIO36, GPIO39 }"' make BOARD=esp32-wroom-32 -C tests/periph_adc/ flash term
```
If these GPIOs work, it might be possible for you to work around.

I have to take a more detailed look how the ADC2 controller is affected by the WiFi module.

**Comment by gschorcht** [comment] 2019-10-19 13:33
Unfortunatly, it is not a bug in the RIOT port for ESP32. According to the [documentation of the original ESP32 SDK](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/adc.html), ADC2 is used by the WiFi driver and can't be used as ADC inputs when the WiFi module is enabled.

Please only use GPIOs from 32 to 39 which are realized by ADC1.

**Comment by mmaxus35** [comment] 2019-10-19 17:17
Thanks for your help. I should have thought these restrictions at first
place. I just could not think that why a wifi dedicated chip has a
restriction for an important feature like 12 bit resolution. I am sorry to
take your time. I will be more careful at next issue. I will use 10-bit
ones.

19 Eki 2019 Cmt 16:33 tarihinde Gunar Schorcht <notifications@github.com>
şunu yazdı:

**Closed** 2019-10-19 17:19 UTC
