### ISSUE TITLE
General 802.15.4/CC2538 RF driver dislikes fast ACKs

### ISSUE THREAD

**Issue by Gr3yh0und** [RIOT-OS/RIOT#7304] opened 2017-07-03 17:15 UTC
Hey,
I'm using two CC2538DK, one with the gnrc_border_router fw and another with my own. However as soon as I configure both with the AUTOACK and ACK_REQ options I get problems when I am sending packets fast.
E.g. when I send two packets immediately from the client to the router, the router/slip only sends one ACK for the second packet.

Has anyone tested that?

**Comment by roberthartung** [comment] 2017-07-04 06:45
Quick notice: the same happened to me on the AT86RF2XX where I tried to send packages as fast as possible which resulted in missing Interrupts and strange behaviours.

**Comment by Gr3yh0und** [comment] 2017-07-04 06:48
Thanks for the feedback, so it looke like a more general issue. I am currently on the 2017.04 Release (as additional information).

**Comment by smlng** [comment] 2017-07-05 15:39
FYI: the cc2538 does not handle ACKs, they are currently filtered out - cause the device cannot handle them, which has to be done in a software MAC layer. 

In general, you get strange behaviour when sending either to fast, i.e., lots of small packets or large packets that get fragmented by 6LoWPAN for instance.

**Comment by Gr3yh0und** [comment] 2017-07-11 08:17
It looks like the cc2538 is able to do hardware acks - or am I mistaken? I don't have much experience on that field but [Contiki ](https://github.com/contiki-os/contiki/blob/master/cpu/cc2538/dev/cc2538-rf.c#L365)and [OpenThread ](https://github.com/openthread/openthread/blob/master/examples/platforms/cc2538/radio.c#L255) are simply setting the `RFCORE_XREG_FRMCTRL0_AUTOACK` which is according to [here](http://ala.isti.cnr.it/svn/wnlab/MONSTER/it.cnr.isti.monster.firmwares/ZStack%202.6.2%20for%20IAR%208.30/Z-Stack/Components/driverlib/cc2538/inc/hw_rfcore_xreg.h) responsible for sending hw acks. Maybe thats a way how to do it as well in RIOT?

**Comment by smlng** [comment] 2017-07-11 08:42
IIRC that's the case in RIOT as well, if a frame with ACK flag set is received the cc2538 sends an ACK back. The problem is rather the other way around, when the cc2538 sends a frame with ACK flags set and the receiver sends an ACK back, the cc2538 does not have any routines to handle the ACK internally but would pass it up to the (software) driver, that is RIOT. Currently, there is no software MAC for the cc2538 enabled that would handle such ACKs. 

Please also see  #5869 and reference discussion in their for further information on this.

**Comment by Gr3yh0und** [comment] 2017-07-11 08:44
Ah thanks, for the heads up. Now I'm getting it and it makes sense though.

**Comment by PeterKietzmann** [comment] 2019-10-22 19:52
IMO this is still present so I'm reopening it. @jia200x I'm mentioning you just so you're aware of this.

**Comment by miri64** [comment] 2019-10-22 20:19
Given https://github.com/RIOT-OS/RIOT/issues/7304#issuecomment-312794127 this might be related to #11256.

**Comment by jia200x** [comment] 2019-10-23 09:08
> Given #7304 (comment) this might be related to #11256.

IMO that completely explains the problem. The framebuffer gets a lot of IO operations with soft ACKs

**Comment by roberthartung** [comment] 2019-10-23 09:27
@miri64 I would be happy to run some tests on this!

**Comment by miri64** [comment] 2020-07-01 12:44
> @miri64 I would be happy to run some tests on this!

_waits several month with reply_ That would be great!

**Comment by maribu** [comment] 2022-09-16 13:06
ping?

**Comment by miri64** [comment] 2022-09-19 09:59
Could have been solved with the move to 802.15.4 HAL. However, this should be tested. @jia200x maybe?

**Comment by jia200x** [comment] 2022-09-19 11:32
this is definitely not present anymore, as we have performed [severe stress tests](https://github.com/RIOT-OS/RIOT/pull/16946) and never saw an issue like that.
I propose to just close this one.

**Closed** 2022-09-19 11:38 UTC
Labels: Type: bug, Area: network, Area: drivers
