### ISSUE TITLE
gnrc_netif, gnrc_uhcpc: Replacing prefix on border router results in no configured prefix

### ISSUE THREAD

**Issue by bergzand** [RIOT-OS/RIOT#8172] opened 2017-11-29 11:45 UTC
Scenario: Launch the gnrc_border_router on the platform of choice. First use the uhcpd to add a first prefix, then restart it with a different prefix.

Expected result: The node first has the initial prefix and address configured on the wireless interface, later this is replaced by the second prefix.

Observed result: The node first has the initial prefix. Later this is removed, but the new prefix is never added.

Probably caused by the combination of gnrc_uhcpc (correctly) first configuring the new prefix and then removing the old one and the default limit of 2 IPv6-addresses per interface.

Proposed solution: Let gnrc_uhcpc check whether the addition of the new prefix succeeded and if it didn't succeed try to add it again after removal of the old prefix.

**Comment by miri64** [comment] 2020-07-01 15:24
This should be fixed since https://github.com/RIOT-OS/RIOT/pull/13560 and I was not able to reproduce this as described.

<details>

```
[mlenders@sofia RIOT]<3 IPV6_PREFIX=2001:db8:0:1::/64 make -C examples/gnrc_border_router/ term
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_border_router'
make -C ethos
make[2]: Nothing to be done for 'all'.
make -C uhcpd
make[2]: Nothing to be done for 'all'.
make -C sliptty
make[2]: Nothing to be done for 'all'.
sudo sh /home/mlenders/Repositories/RIOT-OS/RIOT/dist/tools/ethos/start_network.sh  /dev/ttyACM0 tap0 2001:db8:0:1::/64 115200
net.ipv6.conf.tap0.forwarding = 1
net.ipv6.conf.tap0.accept_ra = 0
----> ethos: sending hello.
----> ethos: activating serial pass through.
----> ethos: hello reply received
uhcp_client(): no reply received
uhcp_client(): sending REQ...
got packet from fe80::e0bc:7dff:fecb:f54f port 47732
uhcp: push from fe80::e0bc:7dff:fecb:f54f:47732 prefix=2001:db8:0:1::/64
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8:0:1:28ab:dc15:5401:647b/64
gnrc_uhcpc: uhcp_handle_prefix(): configured new prefix 2001:db8:0:1:28ab:dc15:5401:647b/64
ifconfig
ifconfig
Iface  7  HWaddr: 7E:CD:D6:6D:4E:44 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::7ccd:d6ff:fe6d:4e44  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff6d:4e44
          inet6 group: ff02::1:ff00:2
          
Iface  6  HWaddr: 67:E6  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 2A:AB:DC:15:54:01:64:7B 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::28ab:dc15:5401:647b  scope: link  VAL
          inet6 addr: 2001:db8:0:1:28ab:dc15:5401:647b  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff01:647b
          
> ^CCleaning up...
make: *** [/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_border_router/../../Makefile.include:719: term] Error 130

[mlenders@sofia RIOT]<3 IPV6_PREFIX=2001:db8:0:2::/64 make -C examples/gnrc_border_router/ term
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_border_router'
make -C ethos
make[2]: Nothing to be done for 'all'.
make -C uhcpd
make[2]: Nothing to be done for 'all'.
make -C sliptty
make[2]: Nothing to be done for 'all'.
sudo sh /home/mlenders/Repositories/RIOT-OS/RIOT/dist/tools/ethos/start_network.sh  /dev/ttyACM0 tap0 2001:db8:0:2::/64 115200
net.ipv6.conf.tap0.forwarding = 1
net.ipv6.conf.tap0.accept_ra = 0
----> ethos: sending hello.
----> ethos: activating serial pass through.
----> ethos: hello reply received
ifconfig
ifconfig
Iface  7  HWaddr: 7E:CD:D6:6D:4E:44 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::7ccd:d6ff:fe6d:4e44  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff6d:4e44
          inet6 group: ff02::1:ff00:2
          
Iface  6  HWaddr: 67:E6  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 2A:AB:DC:15:54:01:64:7B 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::28ab:dc15:5401:647b  scope: link  VAL
          inet6 addr: 2001:db8:0:1:28ab:dc15:5401:647b  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff01:647b
          
> uhcp_client(): sending REQ...
got packet from fe80::e0bc:7dff:fecb:f54f port 39230
uhcp: push from fe80::e0bc:7dff:fecb:f54f:39230 prefix=2001:db8:0:2::/64
gnrc_uhcpc: uhcp_handle_prefix(): removed old prefix 2001:db8:0:1:28ab:dc15:5401:647b/64
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8:0:2:28ab:dc15:5401:647b/64
gnrc_uhcpc: uhcp_handle_prefix(): configured new prefix 2001:db8:0:2:28ab:dc15:5401:647b/64
ifconfig
ifconfig
Iface  7  HWaddr: 7E:CD:D6:6D:4E:44 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::7ccd:d6ff:fe6d:4e44  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff6d:4e44
          inet6 group: ff02::1:ff00:2
          
Iface  6  HWaddr: 67:E6  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 2A:AB:DC:15:54:01:64:7B 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::28ab:dc15:5401:647b  scope: link  VAL
          inet6 addr: 2001:db8:0:2:28ab:dc15:5401:647b  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff01:647b
```

</details>

**Closed by miri64** 2020-07-01 15:24 UTC
Labels: Area: network, Type: bug
