### ISSUE TITLE
Issues using I2C

### ISSUE THREAD

**Issue by HendrikVE** [RIOT-OS/RIOT#14826] opened 2020-08-21 20:50 UTC
I'm developing an I2C driver for the HD44780 LCD controller. The driver is a ported version of my driver written for Arduino. [The Arduino](https://github.com/HendrikVE/Arduino-LiquidCrystalWired) driver works perfectly fine, but the ported [driver for RIOT](https://github.com/HendrikVE/RIOT/commit/82b88cb98eaeb9043f8a1635f10317d687ce3f43) has issues when it comes to creating custom characters. Everything else also works for RIOT but when defining custom characters the driver has serious problems and honestly I don't see the difference. I used the equivalent function calls. Most of the time it looks like the first 5 of 8 rows are written and the others are ignored, but sometimes it produces a lot of bogus pixel output and I don't know why.

It's the same result on an esp32 and an Arduino Nano, so it's not a problem with the hardware platform.

Below you can see what will happen with the Arduino Code vs. the RIOT code. Printing the characters written by the Arduino code from the RIOT code works by the way, so the problem must be something around the `hd44780_i2c_set_custom_symbol` function.

## Arduino
![IMG_20200821_194155_515](https://user-images.githubusercontent.com/9884864/90932204-6e4d9d00-e3fe-11ea-9024-a6e419e1bb64.jpg)

```
void LiquidCrystalWired::setCustomSymbol(
        CustomSymbol customSymbol, uint8_t charmap[]) {

    uint8_t location = customSymbol;
    command(CMD_SET_CGRAM_ADDR | (location << 3));

    uint8_t data[9];
    data[0] = 0x40;
    for (int i = 1; i < 9; i++) {
        data[i] = charmap[i - 1];
    }
    deviceWrite(data, 9);

    command(CMD_SET_DDRAM_ADDR);
}

inline void LiquidCrystalWired::command(uint8_t value) {
    uint8_t data[] = { 0x80, value };
    deviceWrite(data, 2);

    // max execution time for most commands of 37 µs
    delayMicroseconds(50);
}

void LiquidCrystalWired::deviceWrite(uint8_t *data, uint8_t len) {

    _wire->beginTransmission(_deviceAddress);

    _wire->write(data, len);

    _wire->endTransmission();
}
```

## RIOT
![IMG_20200821_193728_231](https://user-images.githubusercontent.com/9884864/90932195-6a217f80-e3fe-11ea-9424-9a843747982a.jpg)

```
void hd44780_i2c_set_custom_symbol(
        hd44780_i2c_t *dev,
        hd44780_i2c_custom_symbol_t custom_symbol, uint8_t charmap[]) {

    uint8_t location = custom_symbol;
    _command(dev, CMD_SET_CGRAM_ADDR | (location << 3));

    uint8_t data[9];
    data[0] = 0x40;
    for (int i = 1; i < 9; i++) {
        data[i] = charmap[i - 1];
    }
    _device_write(dev, data, 9);

    _command(dev, CMD_SET_DDRAM_ADDR);
}

static inline int _command(hd44780_i2c_t *dev, uint8_t value) {
    uint8_t data[] = { 0x80, value };
    int rc = _device_write(dev, data, 2);

    // execution time for most commands is given as 37 µs
    xtimer_usleep(50);

    return rc;
}

static int _device_write(hd44780_i2c_t* dev, uint8_t *data, uint8_t len) {

    i2c_t i2c_dev = dev->params.i2c_dev;

    if (i2c_acquire(i2c_dev) != 0) {
        return -HD44780_ERROR_I2C;
    }

    int rc = i2c_write_bytes(i2c_dev, dev->params.i2c_addr, data, len, 0);

    i2c_release(i2c_dev);

    return rc;
}
```

I would really appreciate any advice you can give me.

**Comment by HendrikVE** [comment] 2020-08-25 00:44
Thanks, I didn't knew about #12665 yet, but I believe that this PR won't help me. My display unit is connected directly by I2C and not by an I/O expansion which I have to talk to by gpio. I've sent an email to the manufacturer asking how the I2C connection was realized, because it's neither mentioned in the datasheet (if one can call it like that) nor visible on hardware (unless I disassemble it). It's a combination of an HD44780 LCD controller and a PCA9633 PWM controller for the RGB backlight, both controllers are accessible by I2C with the same connection.

> have you tried doing only one i2c_acquire() in hd44780_i2c_set_custom_symbol() instead of calling acquire and release separately for command and data?

Just tried that and the result is the same unfortunately :(

**Comment by HendrikVE** [comment] 2020-08-25 08:48
I got an answer back and the controller for connecting the LCD controller to I2C is an AIP31068L and it looks like this:
![Screenshot_20200825_104039](https://user-images.githubusercontent.com/9884864/91153004-f0201d80-e6bf-11ea-889b-333a6d7e6a81.png)
So a direct I2C driver is my only way to get this thing working.

**Comment by benpicco** [comment] 2020-08-25 09:36
Hm that is strange - is it on the same board that you ran the Arduino code on?
You don't happen to have an oscilloscope or logic analyzer to check how the I2C signal differs?

**Comment by HendrikVE** [comment] 2020-08-25 13:12
Yes, I tested all four combinations of (Arduino Nano / ESP32) and (Arduino / RIOT). For the Arduino it works on both correctly but for RIOT it's broken for both boards. But again, only the custom character creation is broken, everything else works fine also for RIOT.

> You don't happen to have an oscilloscope or logic analyzer to check how the I2C signal differs?

No, unfortunately I have no access to an oscilloscope or a logic analyzer right now, but I might simply buy an analyzer then. Does not look too expensive.

**Comment by benpicco** [comment] 2020-08-25 14:10
What does the content of `charmap` look like?
Have you tried printing the data before it gets transmitted to ensure the error is not before the I2C transmission?

**Comment by HendrikVE** [comment] 2020-08-25 15:23
`charmap` looks like this. There are 8 characters in total and the n-th chararacter has the first n rows filled with `0xff`, others are `0x00`
```
uint8_t custom_char_1[] = {
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
};
```

> Have you tried printing the data before it gets transmitted to ensure the error is not before the I2C transmission? (e.g. print the buffer inside _device_write)

The content of charmap was printed correctly. I also replaced the assignment from charmap by a direct assignment with 0xff for all indices. That should turn on all pixels, but the same issue appears.

**Comment by MrKevinWeiss** [comment] 2020-08-31 15:15
Are the symbols that show up with the riot river reproducible? Could it be noise or a speed issue?

**Comment by HendrikVE** [comment] 2020-09-01 16:23
> You don't happen to have an oscilloscope or logic analyzer to check how the I2C signal differs?

I bought a logic analyzer. The analyzer shows me that everything should be alright. I get ACKs for everything.

> Are the symbols that show up with the riot river reproducible? Could it be noise or a speed issue?

There was no pattern, pretty random but I can confirm that it's a I2C bus speed issue. I changed the definition of `I2C0_SPEED` for `esp32-wroom-32` from `I2C_SPEED_FAST` to `I2C_SPEED_NORMAL` and now everything works fine! It seems like it was only a problem for defining characters because it's the only call that sends more than 2 bytes in a row (it sends 9 bytes). The question now is: How do I handle the knowledge about lower I2C bus speed for this hardware in the driver? I mean it's defined within the boards space and I take the guess that a driver shouldn't play with those values.

**Comment by benpicco** [comment] 2020-09-01 16:27
IIRC the i2c driver on esp32 on esp32 is a software implementation. @gschorcht might know more about it's limitations.

**Comment by MrKevinWeiss** [comment] 2020-09-01 18:27
I guess the next question would be is the higher speed cause problems with the signal or does it go too fast for the controller to handle. If it is the signal it can be fixed with some stronger pullup resistors. If the slave has a high capacitive load then the max speed will be limited until you drive it harder (as @gschorcht pointed out to me at one point).

If delays are needed between the i2c frame the so the controller can process them, then you can try a multiframe write.

This means that you would write the first byte with the `I2C_NOSTOP` flag, the following bytes with the `I2C_NOSTOP|I2C_NOSTART` flag and the final (9th) byte with the `I2C_NOSTART` flag. Inbetween you can add some small delays. This may not work on every I2C implementation though as some have hardware limitations.

**Comment by HendrikVE** [comment] 2020-09-02 10:07
@MrKevinWeiss using the flags works for the character creation.

```c
static int _device_write2(hd44780_i2c_t* dev, uint8_t *data, uint8_t len) {

    i2c_t i2c_dev = dev->params.i2c_dev;

    if (i2c_acquire(i2c_dev) != 0) {
        return -HD44780_ERROR_I2C;
    }

    for (int i = 0; i < len; i++) {
        if (i == 0) {
            i2c_write_byte(i2c_dev, dev->params.i2c_addr, data[i], I2C_NOSTOP);
        }
        else if (i == len - 1) {
            i2c_write_byte(i2c_dev, dev->params.i2c_addr, data[i], I2C_NOSTART);
        }
        else {
            i2c_write_byte(i2c_dev, dev->params.i2c_addr, data[i], I2C_NOSTOP | I2C_NOSTART);

            xtimer_usleep(5);
        }
    }

    //int rc = i2c_write_bytes(i2c_dev, dev->params.i2c_addr, data, len, 0);

    i2c_release(i2c_dev);

    return 0;
}
```

The problem when using this function everywhere is that it breaks the initialization phase for some reason. So I would have to keep the old write function and end up with two functions which produces enlarged code size.

Also, if you say that some I2C implementations might have trouble with this hack then this shouldn't be used at all for the final driver. So if there is no way of defining the I2C bus speed without messing up with things I have no other choice left than putting this information about lower bus speed in to a README, right?

**Comment by MrKevinWeiss** [comment] 2020-09-02 14:14
Here is what I would do,

1. In the README indicate that this requires a lower speed I2C bus, maybe point out in the datasheet the max times. Also indicate that it is due to the controller processing and not the physical connection.
2. Add an assert in the driver that checks the speed of the I2C bus is correct. This should at least make it obvious if people are trying to use this driver without reading the documentation.
3. Maybe we should introduce a compile time configuration for max i2c clock speed in lieu of being able to change it runtime. This should be used in the periph_conf.h of the board and can be overridden if this module is selected maybe.

I agree that the above solution is a bit nasty if all that is needed is a slower i2c clk.

**Comment by gschorcht** [comment] 2020-09-02 16:47
First of all I'm sorry for the delay in my answer. I have not been in office for the last few weeks. Here are some comments and questions from my side.

If I understood you correctly, the problem occurs with both Arduino Nano (AVR) and ESP32. Some questions:
- Have you tried it also with other platforms?
- Have you tried the I2C hardware implementation on ESP32? It can be enabled by using module `esp_i2c_hw`.

At least there are no limitations in the I2C software implementation for ESP32.  It works with `I2C_SPEED_FAST_PLUS` and up to 1 MHz clock speed without any problems. I have tested it in multiple drivers and for any length of data transfer. But as @MrKevinWeiss mentioned, a high bus capacity load in combination with wrong pull-up resistors could lead to timing problems. However, such timing problems should also happen if you transfer only one byte. 

After a short look into the datasheet of AiP31068, I'm wondering whether the implementation of the driver might cause a problem. First, you send the command as a full transfer including START and STOP condition. Afterwards, you send the data as separate transfer including START and STOP. The figure in [AiP31068 Datasheet](https://www.newhavendisplay.com/appnotes/datasheets/LCDs/AiP31068.pdf), page 30, gives the impression that the command word and the data transfer has to be combined together in one transfer. Furthermore there is a note _The serial interface doesn't read the Flag (BF), thus it must be waiting enough execution time between two instructions (Refer to Table 4)_ whatever table 4 is. That multiframe write is working, is another hint that the controller might need more time for processing.

I took a short look into your [driver for RIOT code](https://github.com/HendrikVE/RIOT/commit/82b88cb98eaeb9043f8a1635f10317d687ce3f43). Since we already have a driver for `hd44780` and because of the fact that most cheap HD44780 displays with I2C interface on the market that I know use either PCF8574 or PCF8574A as I2C interface, you shouldn't call your driver `hd44780_i2c`. It might be misleading. It should be named more specific, e.g. `hd44780_aip31068` or even `aip31068`. Is your driver implementation specific for `hd44780` or would it also work for other display that are controlled by an AiP31068?

Another option would be to define a common driver interface for HD44780 displays that can use different low level interface drivers.

**Comment by gschorcht** [comment] 2020-09-02 16:58
BTW, the [Liquidcrystalaip31068 Library](https://github.com/red-scorp/LiquidCrystal_AIP31068/blob/master/LiquidCrystal_AIP31068_I2C.cpp) writes a character byte by byte as separate transfers including the START and STOP condition.

**Comment by HendrikVE** [comment] 2020-09-03 17:24
Sorry for my late response.

> Add an assert in the driver that checks the speed of the I2C bus is correct. This should at least make it obvious if people are trying to use this driver without reading the documentation.

That's a good idea. It's not necessary anymore for my driver as you can read later on, but if I would like to add something like an assert or compiler error then there would be a problem because e.g. for the esp32 the bus speed is defined by `I2C0_SPEED` for`I2C_DEV(0)` but for Arduino Nano it is defined (in `board/common/atmega`) by `I2C_BUS_SPEED`. While most boards use a struct `static const i2c_conf_t i2c_config[]` to store a I2C config, the Arduino Nano / atmega does not have this struct at all (see `periph_conf_atmega_common.h`). So it seems like there is no unified way to handle this for all boards. This might be the only deviant case though, I did not check every board.

> Have you tried it also with other platforms?

I could only try again on a nrf52dk but it's difficult due to the lack of proper cables.

> Have you tried the I2C hardware implementation on ESP32? It can be enabled by using module esp_i2c_hw

I activated this module, but the result is the same.

> you shouldn't call your driver hd44780_i2c. It might be misleading.

This was just a temporary name because I was not sure about whether trying to merge this in to the existing hd44780 driver or keep it separate. Even though it's exactly the same "API" for the AiP31068 (as far as I can see) I think it makes more sense to call it `aip31068` as suggested and keep it separate because we are talking to the AiP31068 and not the HD44780 that is hidden behind.

> Is your driver implementation specific for hd44780 or would it also work for other display that are controlled by an AiP31068?

I guess it should work with every HD44780-compatible LCD controller behind an AiP31068 but I'm not sure about that. I don't have the option to test this myself.

> BTW, the Liquidcrystalaip31068 Library writes a character byte by byte as separate transfers including the START and STOP condition. 

Thank you very much for this hint, sending the data bytes this way does indeed work not matter the bus speed! I still don't know why my Arduino version of the driver does not have a problem though, is Arduino operating with a lower bus speed by default?

**Closed** 2020-09-24 12:09 UTC
Labels: Type: question
