### ISSUE TITLE
gnrc/ng_netdev_eth: potential dereferencing nullpointer

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#3261] opened 2015-06-25 11:45 UTC
In ng_netdev_eth the line  [`if (payload)`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/link_layer/ng_netdev_eth/ng_netdev_eth.c#L376) indicates that `payload` might be `NULL`. Some lines below [`_addr_set_multicast(hdr->dst, payload)`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/link_layer/ng_netdev_eth/ng_netdev_eth.c#L399) is called. Inside this function, `payload` is [dereferenced](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/link_layer/ng_netdev_eth/ng_netdev_eth.c#L342). What if `payload` **is** actually `NULL`? I don't know if this is a realistic situation or not. Just close this issue if it's superfluous!

**Comment by authmillenon** [comment] 2015-06-25 12:19
Is this a duplicate of https://github.com/RIOT-OS/RIOT/pull/3238? Can you please refer to the lines you are talking of?

**Comment by authmillenon** [comment] 2015-06-25 12:20
This IS a duplicate of #3238.

**Comment by PeterKietzmann** [comment] 2015-06-25 12:21
Yes it is was a duplicate. PS: I linked the regarding code lines

**Comment by OlegHahm** [comment] 2015-08-18 12:07
With #3238 being closed without merging, I think this is still unfixed.

**Closed** 2015-08-18 14:26 UTC
Labels: duplicate, minor, NSTF, question
