### ISSUE TITLE
ping6: strange statistics 

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4802] opened 2016-02-12 15:14 UTC
I just had a weird result while pinging between nodes:
```
2016-02-12 15:30:14,301 - INFO # 100 packets transmitted, 82 received, 18% packet loss, tim    e 32.0698928 s
2016-02-12 15:30:14,305 - INFO # rtt min/avg/max = 142.044/121.594/157.081 ms
```
I wonder how the average RTT can be smaller than the minimum. ;)

**Comment by authmillenon** [comment] 2016-04-20 15:33
Marked for next release.

**Comment by authmillenon** [comment] 2016-04-20 16:52
Could not reproduce, but the bug fixed in #5377 might be the cause of this.

**Comment by kYc0o** [comment] 2016-07-11 14:12
can anyone confirm if #5377 can be the source of this?

**Comment by kYc0o** [comment] 2016-07-26 12:10
Ok so let's see for the next release (again).

**Comment by miri64** [comment] 2016-07-26 18:06
I think that might have been solved. Lets close this and reopen in case something like this is seen again (it's a minor issue anyways).

**Closed by miri64** 2016-07-26 18:06 UTC
Labels: bug, minor, network
