### ISSUE TITLE
make: feature definitions not working as expected in makefiles

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2058] opened 2014-11-20 13:04 UTC
Compare https://github.com/RIOT-OS/RIOT/pull/1922#issuecomment-61293824

When using a construct like this:

``` make
ifneq (,$(filter periph_rtc,$(FEATURES_PROVIDED)))
       SRC += sc_periph_rtc.c
endif
```

it is never true.

**Comment by haukepetersen** [comment] 2015-08-24 13:28
this issue should be fixed by #3420

**Comment by authmillenon** [comment] 2016-04-20 14:52
That PR was closed. Is it still an issue?

**Comment by OlegHahm** [comment] 2016-06-01 07:58
@LudwigKnuepfer, ping!

**Comment by LudwigKnuepfer** [comment] 2016-06-01 18:57
@OlegHahm pong

**Comment by miri64** [comment] 2016-06-01 18:58
Not an answer to my question ;-)

**Comment by LudwigKnuepfer** [comment] 2016-06-01 19:02
I don't know, maybe you could just test it? A code snippet is in the issue description...

**Comment by miri64** [comment] 2016-06-01 19:11
Nope, still an issue. The problem is that `FEATURES_PROVIDED` is not imported to `sys/shell/commands/Makefile` for some reason (just checked with `$(warning $(FEATURES_PROVIDED))`). Will investigate when I find some time.

**Comment by miri64** [comment] 2016-10-17 11:57
Obviously hadn't had the time to work on this... Anyone care to look into this?

**Closed** 2017-09-08 09:35 UTC
Labels: bug, make
