### ISSUE TITLE
Unable to create a file on my SAM R21 xplained pro board with hello world application

### ISSUE THREAD

**Issue by praveenlark** [RIOT-OS/RIOT#8353] opened 2018-01-12 09:17 UTC
I have flashed hello world application on atmel SAMR21 board with some modifications to create file with fopen. But file is not creating while running hello world program on board.
i Build the and flashed the code with commands
make BOARD=samr21-xpro
sudo make flash BOARD=samr21-xpro

Does anyone have an idea about that?

**Comment by aabadie** [comment] 2018-01-12 09:23
To be helpful we need more details on what you are trying to achieve.
Can you provide a small snippet (in a gist or in a comment of this issue) so we can try to reproduce your issue ?

**Comment by praveenlark** [comment] 2018-01-12 09:34
Here i am providing the snippet of Hello_world code 

int main(void)
{
    puts("Hello World!");

    printf("You are running RIOT on a(n) %s board.\n", RIOT_BOARD);
    printf("This board features a(n) %s MCU.\n", RIOT_MCU);
    FILE *fp = fopen("test.txt", "wb");
    if(fp == NULL) {
        printf("------->Can not create file<----\n");
        //return 0;
    }
     //   printf("found bpkrB file\n");
        putc('A',fp);
    putc('B',fp);
    putc('C',fp);
    fclose(fp);
    fp=fopen("test.txt","r");
    if(fp==NULL)
    {
        printf("\nCan't open file!!!");
        exit(0);
    }

    printf("Contents of file is :\n");
    printf("%c",getc(fp));
    printf("%c",getc(fp));
    printf("%c",getc(fp));

    fclose(fp);
        ssystem("ls -al\n");

    return 0;
}

Hello_world Runtime logs are 

**Hello World!
You are running RIOT on a(n) samr21-xpro board.
This board features a(n) samd21 MCU.
------->Could not create file<----

Can't open file!!!#! exit 0: powering off**

**Comment by miri64** [comment] 2018-01-12 10:41
Hi, first of all, welcome! What does your Makefile look like? What is the SD card reader you are using (AFAIK there is neither an SD card reader nor other flash drive storage on the SAMR21)? Did you include the proper file system module?

**Comment by miri64** [comment] 2018-01-12 10:42
This question might be related to #8339 ;-)

**Comment by miri64** [comment] 2018-01-12 10:43
Another question: you are reading from `test.txt`, so I expect you have it on an SD card somewhere. Did you make sure it is mounted in the path you expect?

**Comment by PeterKietzmann** [comment] 2019-02-21 13:14
No feedback since over a year -> closing. @praveenlark please re-open if the issue persists.

**Closed by PeterKietzmann** 2019-02-21 13:14 UTC
Labels: Type: question
