### ISSUE TITLE
drivers/at86rf2xx: CCA when in Extended Mode

### ISSUE THREAD

**Issue by daniel-k** [RIOT-OS/RIOT#3169] opened 2015-06-05 14:08 UTC
At the moment the at86rf2xx driver issues a manual CCA no matter in which state the transceiver is. Additionally, only the Extended Mode (RX_AACK_ON) is implemented. However the datasheet has some quite explicit sections:

p. 104

> It is not recommended to manually initiate an CCA measurement when using the Extended Operating Mode.

p. 105

> A CCA request should only be initiated in Basic Operating Mode receive states. Otherwise the radio transceiver generates an IRQ_4 (CCA_ED_DONE) and sets the register bit CCA_DONE = 1, even though no CCA measurement was performed.

p. 107

> If a CCA request is initiated in states others than RX_ON or RX_BUSY the PHY generates an IRQ_4 (CCA_ED_DONE) and sets the register bit CCA_DONE, however no CCA was carried out.

Did you test the behaviour in Extended Mode? The datasheet uses _should_ and _recommended_ so I guess CCA might also work in Extended Mode in some cases. What do you think?

**Comment by kaspar030** [comment] 2015-12-18 11:00
(too late for 2015.12)

**Comment by haukepetersen** [comment] 2016-03-31 14:43
@thomaseichinger, @OlegHahm: do we have any news on this?

**Comment by OlegHahm** [comment] 2016-04-01 20:57
I have started to work on this, but with low priority and since it is a new feature, it won't make it for the release.

**Comment by thomaseichinger** [comment] 2016-04-02 16:59
As far as I tested it in the past, triggering CCA requests in software while in extended operation modes never worked. This kind of contradicts p.107
> p. 107

>>If a CCA request is initiated in states others than RX_ON or RX_BUSY the PHY generates an IRQ_4 >>(CCA_ED_DONE) and sets the register bit CCA_DONE, however no CCA was carried out.

**Comment by haukepetersen** [comment] 2016-04-20 12:16
postponed

**Comment by kYc0o** [comment] 2016-07-26 12:50
And postponed again...

**Comment by miri64** [comment] 2016-10-17 13:31
at86rf2xx is not part of GNRC anymore.

**Comment by miri64** [comment] 2016-11-04 16:15
This is not a bug, so I'm postponing it.

**Comment by OlegHahm** [comment] 2016-12-23 10:10
What would be the "right" way to tackle this issue? Disabling the CCA netopt for the current implementation?

**Comment by PeterKietzmann** [comment] 2017-01-10 13:09
It seems no one is actively working on this. I will remove the Milestone completely which must not mean that it's not worth it working on such a great feature.

**Comment by OlegHahm** [comment] 2017-01-14 10:09
I still wonder what is the actual goal of this issue. Implementing basic mode for the transceiver or simply disable the feature for now?

**Comment by OlegHahm** [comment] 2017-01-14 10:32
I propose to go with #6355 first and work on a driver version for the basic operation mode of the at86rf2xx after the release.

**Comment by OlegHahm** [comment] 2017-01-25 14:44
Fixed with #6355 (no CCA in extended mode any more).

**Closed by OlegHahm** 2017-01-25 14:44 UTC
Labels: network, question
