### ISSUE TITLE
tests: xtimer_drift gets stuck on native

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#6052] opened 2016-11-03 15:49 UTC
It was shown in https://github.com/RIOT-OS/Release-Specs/issues/27 that the xtimer_drift currently stops at about ~30-90 seconds on native. I'm not sure if this is related to #5103. In trying to bisect this I reallized that the same thing might also happen in earlier versions but way later (up to 590 seconds I saw).

**Comment by A-Paul** [comment] 2016-11-10 19:03
Just for the record. While testing for 2016.10 RC4 the test has stopped after ~7min, ~3min and ~20min.

**Comment by miri64** [comment] 2016-11-11 00:47
Out of interest I tried this on 2016.10-devel, too: it's also freezing after ~3 min.

**Comment by miri64** [comment] 2016-11-11 11:44
On its introduction the application worked. I leave a longterm bisect run over the weekend ;-)

**Comment by smlng** [comment] 2017-01-31 20:16
I just ran the `xtimer_drift` test on native several times for the `2017.01-RC2` release. It got stuck after 62, 681, and 272 seconds for instance. So not deterministic, however, I did not dig any deeper into this.

**Comment by miri64** [comment] 2017-01-31 20:17
(btw my longterm bisect was as inconclusive as it gets...)

**Comment by smlng** [comment] 2017-02-01 08:17
I narrowed it down to the assembly code [here](https://github.com/RIOT-OS/RIOT/blob/master/cpu/x86/x86_ucontext.c#L60), that is the last function call I see every time before it gets stuck.

My assembly magic is very low, so I didn't dig any deeper ...

**Comment by kYc0o** [comment] 2017-04-25 18:15
I confirm this bug, but I have no idea on the cause... any more hints @smlng ?

**Comment by smlng** [comment] 2017-04-25 18:17
@kYc0o didn't look into this any further, so no 😞

**Comment by haukepetersen** [comment] 2017-10-24 19:21
Just ran the test again for the `2017.10` release spec tests on native: same faulty behavior - tests gets stuck after random intervals.

**Comment by MichelRottleuthner** [comment] 2020-01-24 16:31
Just for reference: in current master (3c13df60abe22e544840a8b9befb39ad3d3bb391) this Issue is still present. Also I'll add the native label as it is only reproducible on native.

**Comment by maribu** [comment] 2022-09-16 13:23
With xtimer on its way out and ztimer being used instead now every, I'd say this is a wontfix.

If anyone disagrees, please reopen.

**Closed by maribu** 2022-09-16 13:23 UTC
Labels: Type: bug, Platform: native, Area: tests, Area: timers
