### ISSUE TITLE
gnrc: potential racey memory leak

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4048] opened 2015-10-05 11:08 UTC
According to the `gnrc_pktbuf_stats()` output the packet buffer contains some chunk when it should be empty. This behavior can be observed when flood-pinging on native to a multicast address (e.g. `ping6 100000 ff02::1 0 0`) if there is more than one receiver (e.g. another native node connected over a bridge with an IPv6 address configured -> Linux and native replies to the ping). It remains unclear if this problem exist only on native (or only with the Ethernet netdev2 driver) and if it happens only for multicast pings. I was not able to provoke a full packet buffer, neither on native nor on real hardware using the unmodified `gnrc_networking` example.

**Comment by cgundogan** [comment] 2015-10-05 11:17
>I was not able to provoke a full packet buffer, neither on native nor on real hardware using the unmodified gnrc_networking example.

Did you test this also with (only) 2 neighbors? I just did a quick test with 4 tap devices and multicast ping. The pinging node crashes quite often (not always).  After several attempts, even a node that was pinged crashed.. but I have no idea why right now. Need to investigate, but I guess it has something to do with all those "possibly lost interrupt" messages

**Comment by kaspar030** [comment] 2015-10-05 11:22
> "possibly lost interrupt" messages

In case you continue digging, they occur if the interrupt handler tries 
to send a message indicating there's an interrupt to handle, but 
msg_try_send fails (e.g., the target is not waiting).

**Comment by authmillenon** [comment] 2015-10-05 11:26
Is it crashing or getting full but stays unreleased? These are two very different problem scopes.

**Comment by authmillenon** [comment] 2015-10-05 11:28
Do we really want to milestone this for this release? I don't see it as a blocker for the release, since it is not a very common use case right now (maybe when we have TCP it becomes one)

**Comment by cgundogan** [comment] 2015-10-05 11:28
Crashing
Am 05.10.2015 13:26 schrieb "Martine Lenders" <notifications@github.com>:

**Comment by OlegHahm** [comment] 2015-10-05 11:57
> Did you test this also with (only) 2 neighbors? 

I tested with 2 to 4 neighbors.

> I just did a quick test with 4 tap devices and multicast ping. The pinging node crashes quite often (not always). After several attempts, even a node that was pinged crashed.. but I have no idea why right now.

Are you sure this is not rather related to https://github.com/RIOT-OS/RIOT/issues/3341 or https://github.com/RIOT-OS/RIOT/issues/3824

> Need to investigate, but I guess it has something to do with all those "possibly lost interrupt" messages

Possibly lost interrupt occurs when the network driver's thread's queue is full.

**Comment by OlegHahm** [comment] 2015-10-05 11:58
> Do we really want to milestone this for this release?

Yes, we do.

> I don't see it as a blocker for the release, since it is not a very common use case right now (maybe when we have TCP it becomes one) 

I don't see it as a blocker, neither. Still a known issue of this release.

**Comment by authmillenon** [comment] 2015-10-05 11:59
Ah, I thought it is a must fix for the release ;-)

**Comment by authmillenon** [comment] 2015-10-05 12:04
With 5 TAPs and the pinging node in GDB (all others just started as binary) I hit https://github.com/RIOT-OS/RIOT/blob/master/cpu/native/native_cpu.c#L144 on the pinging node with `ping6 100000 ff02::1 0 0` at about request seq=38000. The pinged nodes only show `gnrc_netdev2: possibly lost interrupt.` a few (1-4) times

**Comment by authmillenon** [comment] 2015-10-05 12:05
And I just hit `SIGTRAP` again.

**Comment by authmillenon** [comment] 2015-10-05 12:34
https://github.com/RIOT-OS/RIOT/issues/4048#issuecomment-145506696 might point to a scheduler problem in native…

**Comment by authmillenon** [comment] 2015-10-05 12:37
(Doesn't seem to be an issue on `iotlab-m3`, but might also be, that the hardware just isn't fast enough to run into the race condition ^^)

```
1444048548.262235;m3-7;--- ff02::1 ping statistics ---
1444048548.264219;m3-7;10000 packets transmitted, 9945 received, 1% packet loss, time 145.06728901 s
1444048548.265292;m3-7;rtt min/avg/max = 0.387/6.872/49.056 ms
pktbuf
1444048584.182036;m3-11;> pktbuf
1444048584.182864;m3-13;> pktbuf
1444048584.183027;m3-12;> pktbuf
1444048584.183158;m3-7;> pktbuf
1444048584.183269;m3-9;> pktbuf
1444048584.183799;m3-11;packet buffer: first byte: 0x20001c78, last byte: 0x20003478 (size: 6144)
1444048584.184730;m3-11;~ unused: 0x20001c78 (next: 0, size: 6144) ~
1444048584.185397;m3-13;packet buffer: first byte: 0x20001c78, last byte: 0x20003478 (size: 6144)
1444048584.185502;m3-13;~ unused: 0x20001c78 (next: 0, size: 6144) ~
1444048584.185669;m3-12;packet buffer: first byte: 0x20001c78, last byte: 0x20003478 (size: 6144)
1444048584.185766;m3-12;~ unused: 0x20001c78 (next: 0, size: 6144) ~
1444048584.185898;m3-9;packet buffer: first byte: 0x20001c78, last byte: 0x20003478 (size: 6144)
1444048584.186051;m3-9;~ unused: 0x20001c78 (next: 0, size: 6144) ~
1444048584.186183;m3-7;packet buffer: first byte: 0x20001c78, last byte: 0x20003478 (size: 6144)
1444048584.186274;m3-7;~ unused: 0x20001c78 (next: 0, size: 6144) ~
```

**Comment by cgundogan** [comment] 2016-01-05 08:59
@authmillenon could you please confirm whether this problem still persists?

**Comment by authmillenon** [comment] 2016-01-05 10:19
Japp, SIGTRAP on sender, possibly lost interrupt on receiver.

**Comment by OlegHahm** [comment] 2016-01-05 10:22
Isn't this a different problem?

**Comment by authmillenon** [comment] 2016-01-05 10:55
Well the packet buffer is still full of stuff, so I would guess no.

**Comment by authmillenon** [comment] 2016-04-20 15:03
Let's fix this for the next release ;-)

**Comment by kYc0o** [comment] 2016-07-25 16:12
@miri64  It was?

**Comment by miri64** [comment] 2016-07-25 18:09
I honestly don't know. So let's move this again.

**Comment by kaspar030** [comment] 2018-04-20 09:14
Unconfirmed for more than two years -> closing.

**Closed by kaspar030** 2018-04-20 09:14 UTC
Labels: GNRC, bug, network
