### ISSUE TITLE
Support For cc1310 and cc1350

### ISSUE THREAD

**Issue by wamburu** [RIOT-OS/RIOT#6715] opened 2017-03-07 13:15 UTC
Am trying to port this to TI's cc1310 and cc1350 family. 

Is there to do this?
The hello world doesn't seem to work on this.

Thanks.

**Comment by PeterKietzmann** [comment] 2017-03-28 20:55
Hi @denzelwamburu and welcome to RIOT! Can you give some more details about what has been done? Maybe share a branch or open PR with your changes?

**Comment by cvgaviao** [comment] 2017-10-19 12:13
Hi, I'm also interested to use RIOT on CC1310/CC1350 Launchpads and my custom boards with those ICs. 
Anyone have tried to use RIOT/boards/cc2650-launchpad on one of them ?

**Comment by denzelwamburu** [comment] 2017-10-20 09:21
@cvgaviao  I tried but to no avail. My cc1310 board seems it didn't have enough memory

**Comment by cvgaviao** [comment] 2017-10-20 09:37
@denzelwamburu, I will have a try this weekend. 
But enought memory makes no sense because I'm running Contiki on my LaunchPads and what I have read is that Riot is smaller than contiki.

**Comment by PeterKietzmann** [comment] 2017-11-27 17:45
These wiki pages might help you:
- [Porting Guide](https://github.com/RIOT-OS/RIOT/wiki/Porting-Guide)
- [Writing a device driver inRIOT](https://github.com/RIOT-OS/RIOT/wiki/Guide:-Writing-a-device-driver-in-RIOT)
@denzelwamburu, @cvgaviao can you give a quick status update about your efforts?

**Comment by lafka** [comment] 2018-02-18 15:08
I can confirm that CC2650 example works fine for me. Only step i've done is to copy related files from cc2650 in cpu and board directories to their own cc13xx dirs.

**Comment by Marc-Aurele** [comment] 2018-03-02 13:18
Hi,
I'm also very interested in using RIOT on my CC1310 launchpad. I'm just discovering this MCU and it seems to be full of promise. Usually, im using RIOT on my STM32.

**Comment by PeterKietzmann** [comment] 2018-08-22 07:01
@Marc-Aurele, @lafka, @cvgaviao, @wamburu any progress since February?

**Comment by PeterKietzmann** [comment] 2019-02-21 11:14
@maribu no that you seem to be the CC1xxxx radio expert I just wanted you to be aware of this feature request.

**Comment by PeterKietzmann** [comment] 2019-07-17 07:58
It seems there is no ongoing work nor interest in this so I'm closing the issue as it seems very outdated.

**Closed by PeterKietzmann** 2019-07-17 07:58 UTC
Labels: Type: new feature, Type: question
