### ISSUE TITLE
Vagrant: latest vbox (5.1.18) + latest vagrant (1.9.3) don't RIOT together 

### ISSUE THREAD

**Issue by emmanuelsearch** [RIOT-OS/RIOT#6798] opened 2017-03-27 16:11 UTC
I upgraded, and since then, when I `vagrant up` I get the error:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "a6f83dd0-c3a2-4330-88c6-0aabd3cecc56", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'RIOT-VM' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**Comment by emmanuelsearch** [comment] 2017-03-27 16:12
Anyone out there with the same issues?

**Comment by thomaseichinger** [comment] 2017-03-27 19:40
@emmanuelsearch I can't reproduce this, I had to update the VirtualBox Extension kit however too to get rid of the following error message.
```txt
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "54959472-9dcb-427a-b8d5-c7f591ee57b7", "--type", "headless"]

Stderr: VBoxManage: error: Implementation of the USB 3.0 controller not found!
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by emmanuelsearch** [comment] 2017-03-27 20:30
Thanks. By updating the extension pack I could make the setup work, but my (previous) VM seems to not work with the upgrade. I'll investigate further to see if I can salvage it somehow.

**Comment by PeterKietzmann** [comment] 2019-02-21 11:55
@emmanuelsearch this is almost two years old and I think it's outdated. We're currently at vbox 6.0 and vagrant 2.2.3 so I'm closing this one. Please correct me I'd I'm mistaken

**Closed by PeterKietzmann** 2019-02-21 11:55 UTC
Labels: Area: tools
