### ISSUE TITLE
IPHC/NHC broken

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#4462] opened 2015-12-10 17:28 UTC
Following setup:
Linux <-> `gnrc_border_router` example (N1) <-> `microcoap_server` example (N2)

I am able to ping N2 from linux, but I am not able to make CoAP requests.
If I disable iphc with `ifconfig x -iphc` on N1 and N2, then I can do CoAP requests (with Copper) from Linux <-> N2.

I have no time to investigate further right now. Can anyone confirm this behavior? @kaspar030 didn't you state something similar on IRC yesterday?

**Comment by kaspar030** [comment] 2015-12-10 17:32
> @kaspar030 didn't you state something similar on IRC yesterday?

Yep, exactly the same. Wireshark shows a garbled CoAP reply arriving in Linux. Disabling iphc makes it work.

**Comment by OlegHahm** [comment] 2015-12-10 19:53
Can someone check with TFTP or simple netcat? Should be affected, too. But I saw it working while reviewing the NHC PR.

On 10 December 2015 18:32:53 CET, Kaspar Schleiser <notifications@github.com> wrote:
>> @kaspar030 didn't you state something similar on IRC yesterday?
>
>Yep, exactly the same. Wireshark shows a garbled CoAP reply arriving in
>Linux. Disabling iphc makes it work.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RIOT-OS/RIOT/issues/4462#issuecomment-163696862

-- 
Join the RIOT
http://www.riot-os.org

**Comment by authmillenon** [comment] 2015-12-11 07:49
Was this problem apparent before https://github.com/RIOT-OS/RIOT/pull/4189 got merged?

**Comment by OlegHahm** [comment] 2015-12-11 10:48
Before this problem, NHC wouldn't work at all. Since IPHC (including NHC) is enabled per default on Linux, no UDP connection between RIOT and Linux did work.

**Comment by kaspar030** [comment] 2015-12-11 10:51
Isn't IPHC sixlowpan specific?

**Comment by OlegHahm** [comment] 2015-12-11 10:53
Yes.

**Comment by OlegHahm** [comment] 2015-12-11 10:53
Ah, ah, I see. I meant `no UDP connection over 802.15.4 link layer`.

**Comment by kaspar030** [comment] 2015-12-11 11:07
Ok, I got that right. In the setup above, linux <-> 6lr is using IPv6 over ethernet. Seems like 6lr doesn't unpack IPHC stuff correctly when handing it to plain IPv6.

**Comment by authmillenon** [comment] 2015-12-11 11:14
Since the issue is only with UDP traffic and this behavior wasn't appearent with our 2015.09 tests, I strongly suspect that NHC is the problem.

**Comment by jfischer-phytec-iot** [comment] 2015-12-11 11:19
@cgundogan Can you please comment  ```USEMODULE += gnrc_sixlowpan_iphc_nhc``` out and test again?

**Comment by cgundogan** [comment] 2015-12-12 01:23
I can confirm that Linux (netcat) -> N2 (posix udp server) works with iphc. N2 -> Linux doesn't work. This is however a completely different problem (`_implicit_bind` fails because `gnrc_conn6_set_local_addr` returns false).

Nevertheless, CoAP ping/discovery is broken with iphc enabled and works when iphc is disabled. "Normal" udp traffic (induced with netcat) does seem to work with and without iphc enabled.

**Comment by cgundogan** [comment] 2015-12-12 02:12
UDP traffic (posix example - single hop) between two RIOT nodes seems to be broken when iphc is enabled. Disabling iphc on the sending node fixes the problem.

**Comment by cgundogan** [comment] 2015-12-12 18:55
@jfischer-phytec-iot  with `DISABLE_MODULE += gnrc_sixlowpan_iphc_nhc` CoAP works without disabling iphc manually via the ifconfig command

**Comment by authmillenon** [comment] 2015-12-13 13:20
Maybe related to #4397?

**Comment by authmillenon** [comment] 2015-12-18 16:35
Found another issue, that might cause this: Currently IPv6 assumes for forwarding, that nothing is between the IPv6 header and the payload for the pktsnip reversal (https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L824). This is not the case with NHC, since UDP will be between the two. Did not go into it in-depth and did not have a fix yet.

**Comment by cgundogan** [comment] 2015-12-22 10:21
not fixed

**Comment by OlegHahm** [comment] 2015-12-22 10:22
Good catch, thanks

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 16:27
Have wireshark running while testing https://github.com/RIOT-OS/RIOT/pull/4485#issuecomment-166650528, as I see it, the Border Router does not perform NHC decoding.

**riot-node -> riot-6lo**
![rnode-to-r6lo](https://cloud.githubusercontent.com/assets/9864546/11959879/12ac7b1a-a8d0-11e5-8e4f-eb7177e03d20.png)

**riot-6lo -> linux**
![6lo-to-linux](https://cloud.githubusercontent.com/assets/9864546/11959884/1a1a1344-a8d0-11e5-98a1-167f3c85f79e.png)

**Comment by authmillenon** [comment] 2015-12-22 16:29
is it a linux br or a riot br?

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 16:30
riot br (riot-6lo - (over tun) -> linux host)

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 16:42
@authmillenon Oh no, opposite, riot-6lo makes nhc encoding for slip-iface, or?

**Comment by authmillenon** [comment] 2015-12-22 16:43
That would be very weird, because the slip interface shouldn't even go near 6LoWPAN (and why is IPHC not done there too).

**Comment by OlegHahm** [comment] 2015-12-22 16:59
Maybe the slip interface doesn't remove the NHC snip while forwarding or so?

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:07
The second dump looks exact like encoded UDP, src + dst inline, length elided, payload ok. Next Header is wrong ...

**Comment by authmillenon** [comment] 2015-12-22 17:22
I'm sorry, got to go… wasn't able to set up my border router (samr21-xpro with https://github.com/RIOT-OS/RIOT/pull/4212) properly and don't have a UART adapter right now :-/. I suspect the NHC decoding on forwarding not working, other explanation would be very weird. Further investigation into this by others would be much appreciated :-)

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:33
There is no UDP module in the examples/gnrc_border_router, no UDP no NHC decoding :smile:

**Comment by cgundogan** [comment] 2015-12-22 17:34
even after compiling `gnrc_udp` in it still crashes at the 6lr node.. don't know why

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:36
6lo do not forward the udp packet to the node...

**Comment by authmillenon** [comment] 2015-12-22 17:37
> There is no UDP module in the examples/gnrc_border_router, no UDP no NHC decoding :smile:

Why? This is a perfectly good use-case, why NHC without UDP would make sense. If we remove this dependency this should work, right?

**Comment by cgundogan** [comment] 2015-12-22 17:39
my 6lr node crashes, because it tries to send the decoded message to the ipv6 thread (`gnrc_netapi_dispatch_receive()`), but it crashes because the pkt gets traversed in the following order (nettype):
0 (undef) => 4 (udp) => 2 (ipv6) => 65 (???) => 42 (???) => crash

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:41
@cgundogan based on #4485?

>Why? This is a perfectly good use-case, why NHC without UDP would make sense. If we remove this dependency this should work, right?

no, the node (microcoap) sends encoded udp, the 6lo needs nhc to decode it.

**Comment by cgundogan** [comment] 2015-12-22 17:41
btw I am doing my testing with #4485 merged

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:42
crash == hard fault ?

**Comment by cgundogan** [comment] 2015-12-22 17:42
yes and pc showing to nirvana

**Comment by cgundogan** [comment] 2015-12-22 17:43
```
2015-12-22 18:33:57,995 - INFO # Context before hardfault:
2015-12-22 18:33:57,996 - INFO #    r0: 0x0000000a
2015-12-22 18:33:57,997 - INFO #    r1: 0x2000004c
2015-12-22 18:33:57,998 - INFO #    r2: 0x00000000
2015-12-22 18:33:57,999 - INFO #    r3: 0x20006355
2015-12-22 18:33:57,999 - INFO #   r12: 0x00000008
2015-12-22 18:33:58,000 - INFO #    lr: 0x0000079b
2015-12-22 18:33:58,001 - INFO #    pc: 0x00005fb6
2015-12-22 18:33:58,002 - INFO #   psr: 0x21000000
2015-12-22 18:33:58,002 - INFO #
2015-12-22 18:33:58,003 - INFO # Misc
2015-12-22 18:33:58,004 - INFO # EXC_RET: 0xfffffffd
2015-12-22 18:33:58,006 - INFO # Attempting to reconstruct state for debugging...
2015-12-22 18:33:58,007 - INFO # In GDB:
2015-12-22 18:33:58,009 - INFO #   set $pc=0x5fb6
2015-12-22 18:33:58,010 - INFO #   frame 0
2015-12-22 18:33:58,011 - INFO #   bt
```

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:44
6lo over ethernet ? (works for me on samr21)

**Comment by cgundogan** [comment] 2015-12-22 17:46
my setup is: linux (tunslip) <=> gnrc_boarder_example with gnrc_udp module <=> coap example

**Comment by cgundogan** [comment] 2015-12-22 17:47
also testing with samr21

**Comment by cgundogan** [comment] 2015-12-22 17:47
and with #4485 merged

**Comment by authmillenon** [comment] 2015-12-22 17:47
> no, the node (microcoap) sends encoded udp, the 6lo needs nhc to decode it.

Yes, but the border router doesn't need the UDP module, because it only forwards. It does need NHC however to decode properly for SLIP/Ethernet traffic. So the dependency between NHC module and the UDP module must not be.

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:49
>Yes, but the border router doesn't need the UDP module, because it only forwards. It does need NHC however to decode properly for SLIP/Ethernet traffic. So the dependency between NHC module and the UDP module must not be. 

agree, but it exist
```
#ifdef MODULE_GNRC_UDP
            case NHC_UDP_ID:
                printf("6lo iphc: do decode nhc\n");
                payload_offset = iphc_nhc_udp_decode(pkt, dec_hdr, payload_offset);
                break;
#endif
```

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 17:53
@cgundogan have the same test setup

```
b398941 gnrc_udp: fix false assumed packet order
c2d9342 gnrc_sixlowpan: Fix IPHC/NHC packet order problem
b7a7578 Merge pull request #4507 from authmillenon/gnrc_ipv6/fix/no-order-assumptions
83649dd Merge pull request #4531 from Yonezawa-T2/gnrc_avoid_infinite_loop
34974ab Merge pull request #4534 from Yonezawa-T2/gnrc_off_by_1_overrun
5b4ef43 Merge pull request #4532 from Yonezawa-T2/gnrc_safe_no_routers
08ba1f8 gnrc_ipv6_netif: fixed buffer overrun
fe0e58d gnrc_sixlowpan_nd: fixed crash when there are no routers
9108d27 sixlowpan: fixed infinite loop
2d8f6f8 Merge pull request #4500 from haukepetersen/fix_doc_samd21
1ac9a0d Merge pull request #4480 from authmillenon/doc/enh/creating-modules
b5f5f83 doc: add page about creating modules
```

**Comment by cgundogan** [comment] 2015-12-22 18:01
I just did a clean setup and removed all my custom debug statements and merged #4485 again: the same hard fault

**Comment by cgundogan** [comment] 2015-12-22 18:02
BTW: I use the copper firefox plugin to do a CoAP ping. When issueing that CoAP ping, the 6lr crashes

**Comment by jfischer-phytec-iot** [comment] 2015-12-22 18:04
ok, I use libcoap and ```coap-client coap://[affe::d173:4e02:71af:600a]/riot/board```

**Comment by cgundogan** [comment] 2015-12-22 18:46
current status: with `gnrc_udp` compiled into the boarder router, the 6lr node crashes for me when I use any kind of CoAP traffic over the 6lbr. I use samr21-xpros for both nodes. @jfischer-phytec-iot uses a samr21-xpro for the 6lbr and a phynode for the 6lr and his 6lr does not crash when using CoAP traffic.

**Comment by cgundogan** [comment] 2015-12-22 18:47
(on master + #4485)

**Comment by jfischer-phytec-iot** [comment] 2015-12-23 14:00
I have found an other bug in iphc_nhc_udp_encode...

**Comment by cgundogan** [comment] 2015-12-23 14:02
>I have found an other bug in iphc_nhc_udp_encode...

enlighten us please

**Comment by jfischer-phytec-iot** [comment] 2015-12-23 14:08
wip

**Comment by authmillenon** [comment] 2015-12-23 14:14
But #4485 fixed @kaspar030's and @cgundogan's issue?

**Comment by authmillenon** [comment] 2015-12-23 14:15
@jfischer-phytec-iot can you at least sketch out a bug description so we can assess the severity for the release?

**Comment by cgundogan** [comment] 2015-12-23 14:17
> But #4485 fixed @kaspar030's and @cgundogan's issue?

Nope, it didn't fix @kaspar030's and my issue.

**Comment by jfischer-phytec-iot** [comment] 2015-12-23 14:18
I need 20-40 Minutes for a PR, i hope ...

There is also an possible overflow in gnrc_pktbuf_realloc_data, is it known?

**Comment by authmillenon** [comment] 2015-12-23 14:18
Afaik no.

**Comment by jfischer-phytec-iot** [comment] 2015-12-23 15:33
@cgundogan can you please test #4544 ?

**Comment by gebart** [comment] 2016-03-02 10:49
@cgundogan did you test #4544 ?

**Comment by authmillenon** [comment] 2016-03-02 11:04
Maybe #4935 will also help ;-).

**Comment by authmillenon** [comment] 2016-04-19 16:07
This issue is fixed.

**Comment by authmillenon** [comment] 2016-04-19 16:08
(with merging of #5232)

**Closed by authmillenon** 2016-04-19 16:07 UTC
Labels: bug, network, question
