### ISSUE TITLE
pkg/micro-ecc: micro-ecc cannot be built for SAMR21-XPRO board

### ISSUE THREAD

**Issue by wentaoshang** [RIOT-OS/RIOT#5466] opened 2016-05-26 20:55 UTC
micro-ecc patch 0002 in RIOT-OS adds the dependency on hardware rng, which is not available on SAMR21-XPRO board (and many others).  RIOT-OS should fall back to the original software rng in micro-ecc code if the target board does not have periph-hwrng support.

**Comment by OlegHahm** [comment] 2016-05-27 06:20
I am by no means a crypto expert, but still I wonder if it makes sense to base a crypto library on a software PRNG without a good source for seeding it. In other words, shouldn't we find a solution for https://github.com/RIOT-OS/RIOT/issues/3221 first, before we change this?

**Comment by wentaoshang** [comment] 2016-05-27 07:59
I'm not a security expert, either. So I don't know how well the rng in uECC is implemented... But if the board does not have hardware rng support, what other choice do we have except using software rng?

**Comment by gebart** [comment] 2016-05-27 08:41
@wentaoshang the challenge is to find innovative ways to gather entropy for the PRNG and use a cryptographically secure PRNG for the random numbers. (though I am not a cryptographer either)

**Comment by wentaoshang** [comment] 2016-05-27 17:30
I'd like to take a practical approach: why not use the tinymt32 implementation in RIOT-OS as a starting point? Is it too weak to be used for ECC?

**Comment by d00616** [comment] 2016-05-27 18:52
Without hardware RNG there must be implemented a very good pseudo RNG initialized by entropy from various sources. I have no knowledge to do this in a cryptographic save way. I'm not a crypto expert.

The major question is how to get entropy good enough for cryptography. How to get this fast to do cryptographic operations a short time after powering on. If this solved a pseudo RNG can used for faster generation of randomness.

@wentaoshang tinymt32 may a good solution for an pseudo RNG for key sizes up to 128 Bit. Have you FIPS tested it?

**Comment by wentaoshang** [comment] 2016-05-27 19:05
No I haven't done any testing. Not sure how to do "FIPS test"...

**Comment by d00616** [comment] 2016-05-27 19:06
Take a look here: https://wiki.archlinux.org/index.php/Rng-tools

**Comment by kaspar030** [comment] 2016-05-27 19:42
> I'd like to take a pragmatic approach: why not use the tinymt32 implementation in RIOT-OS as a starting point? Is it too weak to be used for ECC?

The problem is that with the same seed value, PRNGs spit out the same numbers in the exact same sequence. So while using tinymt32 as RNG would be OK for starting, we still need to find a way to initially seed it after reboot, in case no HW RNG is available.

**Comment by wentaoshang** [comment] 2016-05-31 19:20
@kaspar030 After a few days of research, I couldn't find a way to seed the PRNG on the boards with no hardware rng. There are rumors that a lot of ARM manufactures actually include HW rng on the chip. But not sure how to make use of that.

So another solution is to use `uECC_sign_deterministic` API. It follows the standard practice defined in RFC6979, which is designed specifically for devices with little or no source of entropy. It simply uses the hash of the private key to generate the random number `k` in ECDSA. Generating the private key still requires strong source of entropy. Therefore we need to generate the key on some other device then copy it over to the IoT board with not HWRNG (which makes sense to me).

This API is pretty easy to use. But I still have problem with linking: gcc must resolve all external references when it prepares the .a file for uECC, but `hwrng_read` is never defined (even though it's never used in the code, either). Is it possible to add some macro tricks so that the 0002 patch is applied only if HWRNG is supported by the board?

**Comment by OlegHahm** [comment] 2016-05-31 19:49
Maybe `FEATURES_PROVIDED` can be used somehow.

**Comment by mtausig** [comment] 2016-07-26 08:01
Introducing a weak RNG is definietely not a good solution. 
But what could be done, is make micro-ecc at least semi-usable without a HWRNG, since a lot of functions does not need it anyway (like signature verification and deterministic signing). One could create a patch which removes all functions requiring random numbers when no hwrng is available.

**Comment by mtausig** [comment] 2016-07-26 08:03
By the way, @wentaoshang: Have a look at https://github.com/RIOT-OS/RIOT/pull/4989, which implements the hwrng for a samr1-xpro board. It is not merged (and won't be in the near future), but it works and you could use it in your project.

**Closed** 2017-01-05 15:38 UTC
Labels: Request for Comments
