### ISSUE TITLE
ESP32 toolchain linked to in doc.txt is broken

### ISSUE THREAD

**Issue by TimoRoth** [RIOT-OS/RIOT#10432] opened 2018-11-19 21:26 UTC
#### Description

From the doc.txt: https://github.com/RIOT-OS/RIOT/blob/master/cpu/esp32/doc.txt#L325

The linked xtensa esp32 toolchain(https://github.com/gschorcht/xtensa-esp32-elf.git) is broken. It comes with gcc configured with --enable-threads=posix, which leads to numerous build errors.

#### Steps to reproduce the issue

Target for example the esp32-wroom-32 board, and use the esp_wifi module.

#### Expected results
A clean build.

#### Actual results
A _long_ list of errors, most/all of them in pthread.h.

#### Solution

Using the older toolchain from https://docs.espressif.com/projects/esp-idf/en/v2.1.1/get-started/linux-setup.html makes things build cleanly for me.
Namely that is https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz

The repo the doc.txt refers to seems to be the 1.22.0-80 version linked to for all the more recent 3.0 esp-idf versions.

**Comment by gschorcht** [comment] 2018-11-19 22:41
Thanks for your detailed report. I already realized the problem which should be fixed with PR #10362.

The problem was caused by the switch from the original toolchain to a self-compiled one which became necessary since `printf` for floats  was not working with the original one. When activating any WiFi module `esp_now` or `esp_wifi`, module `esp_nvs_flash` is used which requires POSIX threads. I guess you get these errors in `$(RIOTBASE)/cpu/esp32/vendor/esp-idf/nvs_flash`.

**Comment by TimoRoth** [comment] 2018-11-20 11:48
Is it right that the new toolchain with the issue has both --disable-threads and --enable-threads=posix on its configure commandline? It seemed like a mistake to me, specially as the older toolchain without --enable-threads=posix works just fine.

**Comment by jcarrano** [comment] 2018-11-21 13:19
Now that #10362 is merged, if this issue is fixed we can close it. I don't quite understand what exactly was the problem, though.

**Comment by gschorcht** [comment] 2018-11-21 13:37
@jcarrano It's a bit tricky. When module `eps_wifi` or `esp_now` is used, module `esp_nvs_flash` is also enabled automatically. In that case, the header files for POSIX threads are required since the toolchain that I provided has been obviously compiled with `--enable-threads=posix` (the default). The original one is compiled with `--enable-threads=posix`. That is, in that case we also need the `posix` module :worried:. I didn't realize that when I switched from original toolchain to the self-compiled one because of the printf problem for floats described in PR #9426.

**Comment by gschorcht** [comment] 2018-11-21 13:40
@jcarrano I will try to recompile the toolchain with `--disable-threads=posix` to provide a version that does not need POSIX threads anymore. I had it already on my to todo list since September.

**Comment by jcarrano** [comment] 2018-11-21 13:40
Sorry, I closed by accident, I won't close this on my own initiative!

**Comment by gschorcht** [comment] 2018-11-21 13:43
Who should close it?

**Comment by jcarrano** [comment] 2018-11-21 14:54
I can close it, or you. I was just waiting for an explicit confirmation from the people who know about this platform. As you said that the toolchain needs recompilation, I was not sure if this was fixed "for real" or not.

**Comment by gschorcht** [comment] 2018-11-21 15:02
Now that #10362 is merged, the problem does not occur any longer independent on whether the toolchain is recompiled or not. Also, the documentation has not to be changed. So we could close this issue from my point of view. @TimoRoth confirmed in PR #10362 that the toolchain is working with this PR.

**Comment by jcarrano** [comment] 2018-11-21 15:04
Ok.

**Closed by jcarrano** 2018-11-21 15:04 UTC
Labels: Area: doc, Area: toolchain, Platform: ESP, Type: bug
